### ISSUE TITLE
Union API Full Name

### ISSUE THREAD

**Issue by draab** [wtg/petitions-old#22]
We should update the app so it pulls the users full name based on the authorized RCS ID. I've been learning the new CMS Union API and figuring out how it works and it returns real names if you provide it an RCS Id which is given by the current CAS system. This would allow for the site to look a little nice and more professional.

I've also confirmed that the WebTech API Key provides this information but I want to consult people before including the Key in our public repo.

**Comment by PranavSathy** [comment]
@draab : It is recommended not to commit the key to a public repository, it should be in a backend service that simply serves the information requested. This is for security reasons :)

**Comment by justetz** [comment]
@PranavSathy : I just went through and checked - the API key is not in the repository. Currently the server code where the API would be states `Authorization: "Token <token>"`. The token would be added to the cloned code directly on the server prior to deployment.

**Comment by PranavSathy** [comment]
@justetz : Cool, just to clarify you can actually say "Token " + process.env.CMS_TOK and you can set that as an environment variable on the production server. <- This would actually be the preferred way :)
